/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.KyNangController;
import model.KyNang;

/**
 *
 * @author thisi
 */
public class CreateNewSkillPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewSkillPanel
     */
    KyNangController kyNangController;
    public CreateNewSkillPanel() {
        initComponents();
        
        kyNangController = new KyNangController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tenInput = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        motaInput = new javax.swing.JTextArea();
        resetButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Kỹ năng");

        jLabel2.setText("Mô tả");

        tenInput.setForeground(new java.awt.Color(153, 153, 153));
        tenInput.setText("Nhập kỹ năng...");
        tenInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tenInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tenInputFocusLost(evt);
            }
        });

        addButton.setText("Thêm mới");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        motaInput.setColumns(20);
        motaInput.setForeground(new java.awt.Color(153, 153, 153));
        motaInput.setRows(5);
        motaInput.setText("Nhập mô tả...");
        motaInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                motaInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                motaInputFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(motaInput);

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(tenInput)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(resetButton)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton)
                            .addComponent(resetButton))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel3.setText("THÊM KỸ NĂNG MỚI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String ten = tenInput.getText();
        String mota = motaInput.getText();
        
        KyNang kn = new KyNang(ten, mota);
        int num = kyNangController.insert(kn);
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        tenInput.setText("");
        motaInput.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void tenInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tenInputFocusGained
        // TODO add your handling code here:
        if (tenInput.getText().equals("Nhập kỹ năng...")) {
            tenInput.setText("");
            tenInput.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_tenInputFocusGained

    private void tenInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tenInputFocusLost
        // TODO add your handling code here:
        if (tenInput.getText().isEmpty()) {
            tenInput.setText("Nhập kỹ năng...");
            tenInput.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_tenInputFocusLost

    private void motaInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motaInputFocusGained
        // TODO add your handling code here:
        if (motaInput.getText().equals("Nhập mô tả...")) {
            motaInput.setText("");
            motaInput.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_motaInputFocusGained

    private void motaInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motaInputFocusLost
        // TODO add your handling code here:
        if (motaInput.getText().isEmpty()) {
            motaInput.setText("Nhập mô tả...");
            motaInput.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_motaInputFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea motaInput;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField tenInput;
    // End of variables declaration//GEN-END:variables
}
