/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.DuAnController;
import controller.KhachHangController;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import model.DuAn;
import model.KhachHang;
import util.Common;

/**
 *
 * @author thisi
 */
public class CreateNewProjectPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewProjectPanel
     */
    KhachHangController khachHangController;
    DuAnController duAnController;

    public CreateNewProjectPanel() {
        initComponents();

        khachHangController = new KhachHangController();
        duAnController = new DuAnController();

        formReady();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tenInput = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        motaInput = new javax.swing.JTextArea();
        startDate = new javax.swing.JSpinner();
        endDate = new javax.swing.JSpinner();
        tenkhInput = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        emailkhInput = new javax.swing.JTextField();
        sodienthoaikhInput = new javax.swing.JTextField();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setText("THÊM DỰ ÁN MỚI");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("Tên");

        jLabel11.setText("Ngày bắt đầu");

        jLabel12.setText("Ngày kết thúc");

        tenInput.setForeground(new java.awt.Color(153, 153, 153));
        tenInput.setText("Nhập tên dự án...");
        tenInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tenInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tenInputFocusLost(evt);
            }
        });

        jLabel16.setText("Mô tả");

        addButton.setText("Thêm mới");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Làm mới");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        motaInput.setColumns(20);
        motaInput.setForeground(new java.awt.Color(153, 153, 153));
        motaInput.setRows(5);
        motaInput.setText("Nhập mô tả...");
        motaInput.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        motaInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                motaInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                motaInputFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(motaInput);

        startDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1756106349557L), null, java.util.Calendar.DAY_OF_MONTH));

        endDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1756106349557L), null, java.util.Calendar.DAY_OF_MONTH));
        endDate.setToolTipText("");

        tenkhInput.setEditable(true);
        tenkhInput.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tenkhInputItemStateChanged(evt);
            }
        });
        tenkhInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenkhInputActionPerformed(evt);
            }
        });

        jLabel14.setText("Tên khách hàng");

        jLabel15.setText("Email khách hàng");

        jLabel17.setText("Số điện thoại");

        emailkhInput.setEditable(false);

        sodienthoaikhInput.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(startDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addButton))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetButton)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(29, 29, 29)
                            .addComponent(tenkhInput, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel17))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sodienthoaikhInput, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailkhInput, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tenkhInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailkhInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sodienthoaikhInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(resetButton))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tenkhInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenkhInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenkhInputActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String ten = tenInput.getText();
        if (ten.isEmpty() || ten.equals("Nhập tên dự án...")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên dự án.");
            return;
        }
        String email = emailkhInput.getText();
        String sodienthoai = sodienthoaikhInput.getText();
        String mota = motaInput.getText();
        if (mota.isEmpty() || mota.equals("Nhập mô tả...")) {
            mota = "";
        }
        Date startDateValue = (Date) startDate.getValue();
        LocalDate start = startDateValue.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Date endDateValue = (Date) endDate.getValue();
                
        LocalDate end = endDateValue.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        KhachHang selected = (KhachHang) tenkhInput.getSelectedItem();
        int maKhachHang = selected.getId();

        DuAn newDuAn = new DuAn(ten, start, end, maKhachHang, mota);

        // Call the controller to add the new project
        int num = duAnController.insert(newDuAn);
        if (num > 0) {
            JOptionPane.showMessageDialog(this, "Thêm dự án thành công!");
            resetForm();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm dự án thất bại!");
        }
        // Reset the form
    }//GEN-LAST:event_addButtonActionPerformed

    private void tenkhInputItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tenkhInputItemStateChanged
        // TODO add your handling code here:
        KhachHang selected = (KhachHang) tenkhInput.getSelectedItem();
        // Use selectedId as needed
        emailkhInput.setText(selected.getEmail());
        sodienthoaikhInput.setText(selected.getSoDienThoai());
    }//GEN-LAST:event_tenkhInputItemStateChanged

    private void tenInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tenInputFocusGained
        // TODO add your handling code here:
        if (tenInput.getText().equals("Nhập tên dự án...")) {
            tenInput.setText("");
            tenInput.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_tenInputFocusGained

    private void tenInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tenInputFocusLost
        // TODO add your handling code here:
        if (tenInput.getText().isEmpty()) {
            tenInput.setText("Nhập tên dự án...");
            tenInput.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_tenInputFocusLost

    private void motaInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motaInputFocusGained
        // TODO add your handling code here:
        if (motaInput.getText().equals("Nhập mô tả...")) {
            motaInput.setText("");
            motaInput.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_motaInputFocusGained

    private void motaInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motaInputFocusLost
        // TODO add your handling code here:
        if (motaInput.getText().isEmpty()) {
            motaInput.setText("Nhập mô tả...");
            motaInput.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_motaInputFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField emailkhInput;
    private javax.swing.JSpinner endDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea motaInput;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField sodienthoaikhInput;
    private javax.swing.JSpinner startDate;
    private javax.swing.JTextField tenInput;
    private javax.swing.JComboBox<KhachHang> tenkhInput;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
        tenInput.setText("Nhập tên dự án...");
        tenInput.setForeground(new java.awt.Color(153, 153, 153));
        motaInput.setText("Nhập mô tả...");
        motaInput.setForeground(new java.awt.Color(153, 153, 153));
        startDate.setValue(new java.util.Date());
        endDate.setValue(new java.util.Date());
    }

    private void formReady() {
        List<KhachHang> dsKhachHang = khachHangController.getAll();
        tenkhInput.removeAllItems();
        for (KhachHang kh : dsKhachHang) {
            tenkhInput.addItem(kh);
        }

        // format spinner
        startDate.setEditor(new JSpinner.DateEditor(startDate, "yyyy-MM-dd"));
        endDate.setEditor(new JSpinner.DateEditor(endDate, "yyyy-MM-dd"));
    }
    
}
