/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.FreelancerController;
import controller.KyNangController;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import model.Freelancer;
import model.KyNang;

/**
 *
 * @author thisi
 */
public class CreateNewFreelancerPanel extends javax.swing.JPanel {

    /**
     * Creates new form createNewFreelancerPanel
     */
    private FreelancerController freelancerController;
    private KyNangController kyNangController;

    public CreateNewFreelancerPanel() {
        initComponents();
        freelancerController = new FreelancerController();
        kyNangController = new KyNangController();
        formReady();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gioitinhButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hotenInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        phoneInput = new javax.swing.JTextField();
        diachiInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addNewButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        namRadio = new javax.swing.JRadioButton();
        nuRadio = new javax.swing.JRadioButton();
        KyNangScrollPane = new javax.swing.JScrollPane();
        ngaysinhSpinner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Họ tên");

        jLabel2.setText("Email");

        jLabel3.setText("Số điện thoại");

        jLabel4.setText("Ngày sinh");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Giới tính");

        hotenInput.setForeground(new java.awt.Color(153, 153, 153));
        hotenInput.setText("Nhập họ tên...");
        hotenInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hotenInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hotenInputFocusLost(evt);
            }
        });

        emailInput.setForeground(new java.awt.Color(153, 153, 153));
        emailInput.setText("Nhập email...");
        emailInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailInputFocusLost(evt);
            }
        });

        phoneInput.setForeground(new java.awt.Color(153, 153, 153));
        phoneInput.setText("Nhập số điện thoại...");
        phoneInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneInputFocusLost(evt);
            }
        });

        diachiInput.setForeground(new java.awt.Color(153, 153, 153));
        diachiInput.setText("Nhập địa chỉ...");
        diachiInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                diachiInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                diachiInputFocusLost(evt);
            }
        });

        jLabel7.setText("Kỹ năng");

        addNewButton.setText("Thêm mới");
        addNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        namRadio.setText("Nam");
        namRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namRadioActionPerformed(evt);
            }
        });

        nuRadio.setText("Nữ");

        KyNangScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        ngaysinhSpinner.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(45, 45, 45)
                        .addComponent(namRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nuRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(addNewButton)
                                .addGap(18, 18, 18)
                                .addComponent(resetButton)))
                        .addGap(18, 18, 18)
                        .addComponent(KyNangScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneInput, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(emailInput, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(diachiInput, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(hotenInput, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(ngaysinhSpinner))
                        .addGap(54, 54, 54))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hotenInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ngaysinhSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diachiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuRadio)
                            .addComponent(jLabel6)
                            .addComponent(namRadio)))
                    .addComponent(KyNangScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewButton)
                    .addComponent(resetButton))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jLabel9.setText("THÊM FREELANCER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void namRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namRadioActionPerformed

    private void hotenInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hotenInputFocusGained
        // TODO add your handling code here:
        if (hotenInput.getText().equals("Nhập họ tên...")) {
            hotenInput.setText("");
            hotenInput.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_hotenInputFocusGained

    private void hotenInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hotenInputFocusLost
        // TODO add your handling code here:
        if (hotenInput.getText().isEmpty()) {
            hotenInput.setText("Nhập họ tên...");
            hotenInput.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_hotenInputFocusLost

    private void emailInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailInputFocusGained
        // TODO add your handling code here:
        if (emailInput.getText().equals("Nhập email...")) {
            emailInput.setText("");
            emailInput.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_emailInputFocusGained

    private void emailInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailInputFocusLost
        // TODO add your handling code here:
        if (emailInput.getText().isEmpty()) {
            emailInput.setText("Nhập email...");
            emailInput.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_emailInputFocusLost

    private void phoneInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneInputFocusGained
        // TODO add your handling code here:
        if (phoneInput.getText().equals("Nhập số điện thoại...")) {
            phoneInput.setText("");
            phoneInput.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_phoneInputFocusGained

    private void phoneInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneInputFocusLost
        // TODO add your handling code here:
        if (phoneInput.getText().isEmpty()) {
            phoneInput.setText("Nhập số điện thoại...");
            phoneInput.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_phoneInputFocusLost

    private void diachiInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diachiInputFocusGained
        // TODO add your handling code here:
        if (diachiInput.getText().equals("Nhập địa chỉ...")) {
            diachiInput.setText("");
            diachiInput.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_diachiInputFocusGained

    private void diachiInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diachiInputFocusLost
        // TODO add your handling code here:
        if (diachiInput.getText().isEmpty()) {
            diachiInput.setText("Nhập địa chỉ...");
            diachiInput.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_diachiInputFocusLost

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        hotenInput.setText("Nhập họ tên...");
        hotenInput.setForeground(new java.awt.Color(153, 153, 153));
        emailInput.setText("Nhập email...");
        emailInput.setForeground(new java.awt.Color(153, 153, 153));
        phoneInput.setText("Nhập số điện thoại...");
        phoneInput.setForeground(new java.awt.Color(153, 153, 153));
        diachiInput.setText("Nhập địa chỉ...");
        diachiInput.setForeground(new java.awt.Color(153, 153, 153));
        gioitinhButtonGroup.clearSelection();
        for (JCheckBox cb : checkBoxes.values()) {
            cb.setSelected(false);
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void addNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewButtonActionPerformed
        // TODO add your handling code here:
        String hoTen = hotenInput.getText();
        if (hoTen.isEmpty() || hoTen.equals("Nhập họ tên...")) {
            JOptionPane.showMessageDialog(this, "Họ tên không được để trống!");
            return;
        }
        String email = emailInput.getText();
        if (email.isEmpty() || email.equals("Nhập email...")) {
            JOptionPane.showMessageDialog(this, "Email không được để trống!");
            return;
        }
        String soDienThoai = phoneInput.getText();
        if (soDienThoai.isEmpty() || soDienThoai.equals("Nhập số điện thoại...")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống!");
            return;
        }
        String diaChi = diachiInput.getText();
        if (diaChi.isEmpty() || diaChi.equals("Nhập địa chỉ...")) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống!");
            return;
        }
        String gioiTinh = namRadio.isSelected() ? "Nam" : "Nữ";
        if (!namRadio.isSelected() && !nuRadio.isSelected()) {
            JOptionPane.showMessageDialog(this, "Giới tính không được để trống!");
            return;
        }
        Date dob = (Date) ngaysinhSpinner.getValue();
        LocalDate ngaySinh = dob.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        // Validate and create Freelancer object
        Freelancer freelancer = new Freelancer();
        freelancer.setHoTen(hoTen);
        freelancer.setEmail(email);
        freelancer.setSoDienThoai(soDienThoai);
        freelancer.setDiaChi(diaChi);
        freelancer.setGioiTinh(gioiTinh);
        freelancer.setNgaySinh(ngaySinh);

        // Call controller to add freelancer
        int num = freelancerController.insert(freelancer);
        if (num > 0) {
            // Get selected skills
            for (Map.Entry<Integer, JCheckBox> entry : checkBoxes.entrySet()) {
                Integer key = entry.getKey();
                JCheckBox cb = entry.getValue();
                if (cb.isSelected()) {
                    freelancerController.insertFreelancerKyNang(freelancer.getId(), key);
                }
            }
            JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm mới thất bại!");
        }
    }//GEN-LAST:event_addNewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane KyNangScrollPane;
    private javax.swing.JButton addNewButton;
    private javax.swing.JTextField diachiInput;
    private javax.swing.JTextField emailInput;
    private javax.swing.ButtonGroup gioitinhButtonGroup;
    private javax.swing.JTextField hotenInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton namRadio;
    private javax.swing.JSpinner ngaysinhSpinner;
    private javax.swing.JRadioButton nuRadio;
    private javax.swing.JTextField phoneInput;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
    private final Map<Integer, JCheckBox> checkBoxes = new LinkedHashMap<>();

    private void addSkillsToScrollPane() {

        JPanel skillsPanel = new JPanel();
        skillsPanel.setLayout(new BoxLayout(skillsPanel, BoxLayout.Y_AXIS));
        List<KyNang> dsKyNang = kyNangController.getAll();
        for (KyNang kyNang : dsKyNang) {
            JCheckBox cb = new JCheckBox(kyNang.getTen());
            checkBoxes.put(kyNang.getId(), cb);
            skillsPanel.add(cb);
        }
        KyNangScrollPane.setViewportView(skillsPanel);
    }
    
    private void formReady() {
        addSkillsToScrollPane();
        
        // format spinner
        JSpinner.DateEditor editor = new JSpinner.DateEditor(ngaysinhSpinner, "yyyy-MM-dd");
        ngaysinhSpinner.setEditor(editor);

        // group button
        gioitinhButtonGroup.add(namRadio);
        gioitinhButtonGroup.add(nuRadio);
    }

}
