/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import model.User;
import util.SessionManager;
import view.CreateNewCustomerPanel;
import view.CreateNewFreelancerPanel;
import view.CreateNewProjectPanel;
import view.CreateNewSkillPanel;
import view.CustomerListPanel;
import view.EditUserDetailPanel;
import view.ProjectListPanel;
import view.SkillListPanel;
import view.UserDetailPanel;

/**
 *
 * @author thisi
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        handleLoginInfo();
        cl = (java.awt.CardLayout) mainPanel.getLayout();
        initPanels(mainPanel, cl);
        setGroupLayout();
        cl.show(mainPanel, FREELANCER_LIST); // default panel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mainMenu = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        freelancerMenu = new javax.swing.JMenu();
        freelancerListMenuItem = new javax.swing.JMenuItem();
        createNewFreelancerMenuItem = new javax.swing.JMenuItem();
        customerMenu = new javax.swing.JMenu();
        CustomerListMenuItem = new javax.swing.JMenuItem();
        CreateNewCustomerMenuItem = new javax.swing.JMenuItem();
        projectMenu = new javax.swing.JMenu();
        projectListMenuItem = new javax.swing.JMenuItem();
        createNewProjectMenuItem = new javax.swing.JMenuItem();
        plainingMenuItem = new javax.swing.JMenuItem();
        skillMenu = new javax.swing.JMenu();
        skillListMenuItem = new javax.swing.JMenuItem();
        createNewSkillMenuItem = new javax.swing.JMenuItem();
        userMenu = new javax.swing.JMenu();
        userDetailMenuItem = new javax.swing.JMenuItem();
        editUserDetailMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        userListMenuItem = new javax.swing.JMenuItem();
        createNewUserMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý Freelancer");
        setLocationByPlatform(true);

        mainPanel.setLayout(new java.awt.CardLayout());

        mainMenu.setText("Main");

        logoutMenuItem.setText("Đăng xuất");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        mainMenu.add(logoutMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        mainMenu.add(exitMenuItem);

        jMenuBar1.add(mainMenu);

        freelancerMenu.setText("Freelancer");

        freelancerListMenuItem.setText("Danh sách freelancer");
        freelancerListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freelancerListMenuItemActionPerformed(evt);
            }
        });
        freelancerMenu.add(freelancerListMenuItem);

        createNewFreelancerMenuItem.setText("➕ Thêm mới");
        createNewFreelancerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewFreelancerMenuItemActionPerformed(evt);
            }
        });
        freelancerMenu.add(createNewFreelancerMenuItem);

        jMenuBar1.add(freelancerMenu);

        customerMenu.setText("Khách hàng");

        CustomerListMenuItem.setText("Danh sách khách hàng");
        CustomerListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerListMenuItemActionPerformed(evt);
            }
        });
        customerMenu.add(CustomerListMenuItem);

        CreateNewCustomerMenuItem.setText("➕ Thêm mới");
        CreateNewCustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewCustomerMenuItemActionPerformed(evt);
            }
        });
        customerMenu.add(CreateNewCustomerMenuItem);

        jMenuBar1.add(customerMenu);

        projectMenu.setText("Dự án");
        projectMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectMenuActionPerformed(evt);
            }
        });

        projectListMenuItem.setText("Danh sách dự án");
        projectListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectListMenuItemActionPerformed(evt);
            }
        });
        projectMenu.add(projectListMenuItem);

        createNewProjectMenuItem.setText("➕ Thêm dự án mới");
        createNewProjectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewProjectMenuItemActionPerformed(evt);
            }
        });
        projectMenu.add(createNewProjectMenuItem);

        plainingMenuItem.setBackground(new java.awt.Color(255, 255, 204));
        plainingMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        plainingMenuItem.setForeground(new java.awt.Color(51, 51, 255));
        plainingMenuItem.setText("Lập kế hoạch");
        plainingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plainingMenuItemActionPerformed(evt);
            }
        });
        projectMenu.add(plainingMenuItem);

        jMenuBar1.add(projectMenu);

        skillMenu.setText("Kỹ năng");

        skillListMenuItem.setText("Danh sách kỹ năng");
        skillListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skillListMenuItemActionPerformed(evt);
            }
        });
        skillMenu.add(skillListMenuItem);

        createNewSkillMenuItem.setText("➕ Thêm mới");
        createNewSkillMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewSkillMenuItemActionPerformed(evt);
            }
        });
        skillMenu.add(createNewSkillMenuItem);

        jMenuBar1.add(skillMenu);

        userMenu.setText("Hồ sơ");

        userDetailMenuItem.setText("Chi tiết");
        userDetailMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDetailMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(userDetailMenuItem);

        editUserDetailMenuItem.setText("Điều chỉnh");
        editUserDetailMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserDetailMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(editUserDetailMenuItem);

        jMenuBar1.add(userMenu);

        jMenu1.setText("Người dùng");

        userListMenuItem.setText("Danh sách người dùng");
        userListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userListMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(userListMenuItem);

        createNewUserMenuItem.setText("➕ Thêm người dùng");
        createNewUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewUserMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(createNewUserMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createNewSkillMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewSkillMenuItemActionPerformed
        // TODO add your handling code here:
        System.out.println("tạo kỹ năng mới");
        cl.show(mainPanel, CREATE_NEW_SKILL);
    }//GEN-LAST:event_createNewSkillMenuItemActionPerformed

    private void freelancerListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freelancerListMenuItemActionPerformed
        // TODO add your handling code here:
        System.out.println("danh sách freelancers");
        cl.show(mainPanel, FREELANCER_LIST);
    }//GEN-LAST:event_freelancerListMenuItemActionPerformed

    private void createNewFreelancerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewFreelancerMenuItemActionPerformed
        // TODO add your handling code here:
        System.out.println("tạo freelancer mới");
        cl.show(mainPanel, CREATE_NEW_FREELANCER);
    }//GEN-LAST:event_createNewFreelancerMenuItemActionPerformed

    private void createNewProjectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewProjectMenuItemActionPerformed
        // TODO add your handling code here:
        System.out.println("tạo dự án mới");
        cl.show(mainPanel, CREATE_NEW_PROJECT);
    }//GEN-LAST:event_createNewProjectMenuItemActionPerformed

    private void skillListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skillListMenuItemActionPerformed
        // TODO add your handling code here:
        System.out.println("danh sách kỹ năng");
        cl.show(mainPanel, SKILL_LIST);
    }//GEN-LAST:event_skillListMenuItemActionPerformed

    private void userDetailMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDetailMenuItemActionPerformed
        // TODO add your handling code here:
        System.out.println("Chi tiết người dùng");
        cl.show(mainPanel, USER_DETAIL);
    }//GEN-LAST:event_userDetailMenuItemActionPerformed

    private void editUserDetailMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserDetailMenuItemActionPerformed
        // TODO add your handling code here:
        System.out.println("Chỉnh sửa thông tin người dùng");
        cl.show(mainPanel, EDIT_USER_DETAIL);
    }//GEN-LAST:event_editUserDetailMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
        dispose();
        new LoginJFrame().setVisible(true);
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void projectListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectListMenuItemActionPerformed
        // TODO add your handling code here:
        System.out.println("Danh sách dự án");
        cl.show(mainPanel, PROJECT_LIST);
    }//GEN-LAST:event_projectListMenuItemActionPerformed

    private void projectMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectMenuActionPerformed
        // TODO add your handling code here:
        System.out.println("danh sách dự án");
        cl.show(mainPanel, PROJECT_LIST);
    }//GEN-LAST:event_projectMenuActionPerformed

    private void CreateNewCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewCustomerMenuItemActionPerformed
        // TODO add your handling code here:
        cl.show(mainPanel, CREATE_NEW_CUSTOMER);
    }//GEN-LAST:event_CreateNewCustomerMenuItemActionPerformed

    private void CustomerListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerListMenuItemActionPerformed
        // TODO add your handling code here:
        cl.show(mainPanel, CUSTOMER_LIST);
    }//GEN-LAST:event_CustomerListMenuItemActionPerformed

    private void plainingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plainingMenuItemActionPerformed
        // TODO add your handling code here:
        cl.show(mainPanel, PLAINING);
    }//GEN-LAST:event_plainingMenuItemActionPerformed

    private void userListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userListMenuItemActionPerformed
        // TODO add your handling code here:
        cl.show(mainPanel, USER_LIST);
    }//GEN-LAST:event_userListMenuItemActionPerformed

    private void createNewUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewUserMenuItemActionPerformed
        // TODO add your handling code here:
        cl.show(mainPanel, CREATE_NEW_USER);
    }//GEN-LAST:event_createNewUserMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CreateNewCustomerMenuItem;
    private javax.swing.JMenuItem CustomerListMenuItem;
    private javax.swing.JMenuItem createNewFreelancerMenuItem;
    private javax.swing.JMenuItem createNewProjectMenuItem;
    private javax.swing.JMenuItem createNewSkillMenuItem;
    private javax.swing.JMenuItem createNewUserMenuItem;
    private javax.swing.JMenu customerMenu;
    private javax.swing.JMenuItem editUserDetailMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem freelancerListMenuItem;
    private javax.swing.JMenu freelancerMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenu mainMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem plainingMenuItem;
    private javax.swing.JMenuItem projectListMenuItem;
    private javax.swing.JMenu projectMenu;
    private javax.swing.JMenuItem skillListMenuItem;
    private javax.swing.JMenu skillMenu;
    private javax.swing.JMenuItem userDetailMenuItem;
    private javax.swing.JMenuItem userListMenuItem;
    private javax.swing.JMenu userMenu;
    // End of variables declaration//GEN-END:variables

    private String FREELANCER_LIST = "FREELANCER_LIST_PANEL";
    private String CREATE_NEW_FREELANCER = "CREATE_NEW_FREELANCER_PANEL";
    private String PROJECT_LIST = "PROJECT_LIST_PANEL";
    private String CREATE_NEW_PROJECT = "CREATE_NEW_PROJECT_PANEL";
    private String SKILL_LIST = "SKILL_LIST_PANEL";
    private String CREATE_NEW_SKILL = "CREATE_NEW_SKILL_PANEL";
    private String USER_DETAIL = "USER_DETAIL_PANEL";
    private String EDIT_USER_DETAIL = "EDIT_USER_DETAIL_PANEL";
    private String CUSTOMER_LIST = "CUSTOMER_LIST_PANEL";
    private String CREATE_NEW_CUSTOMER = "CREATE_NEW_CUSTOMER_PANEL";
    private String PLAINING = "PLAINING_PANEL";
    private String USER_LIST = "USER_LIST_PANEL";
    private String CREATE_NEW_USER = "CREATE_NEW_USER_PANEL";

    private java.awt.CardLayout cl;

    private FreelancerListPanel freelancerListPanel;
    private CreateNewFreelancerPanel createNewFreelancerPanel;
    private ProjectListPanel projectListPanel;
    private CreateNewProjectPanel createNewProjectPanel;
    private SkillListPanel skillListPanel;
    private CreateNewSkillPanel createNewSkillPanel;
    private UserDetailPanel userDetailPanel;
    private EditUserDetailPanel editUserDetailPanel;
    private CustomerListPanel customerListPanel;
    private CreateNewCustomerPanel createNewCustomerPanel;
    private PlainingPanel plainingPanel;
    private UserListPanel userListPanel;
    private CreateNewUserPanel createNewUserPanel;

    private void initPanels(JPanel mainPanel, CardLayout cl) {
        freelancerListPanel = new FreelancerListPanel(mainPanel, cl);
        createNewFreelancerPanel = new CreateNewFreelancerPanel();
        projectListPanel = new ProjectListPanel(mainPanel, cl);
        createNewProjectPanel = new CreateNewProjectPanel();
        skillListPanel = new SkillListPanel(mainPanel, cl);
        createNewSkillPanel = new CreateNewSkillPanel();
        userDetailPanel = new UserDetailPanel();
        editUserDetailPanel = new EditUserDetailPanel();
        customerListPanel = new CustomerListPanel(mainPanel, cl);
        createNewCustomerPanel = new CreateNewCustomerPanel();
        plainingPanel = new PlainingPanel(mainPanel, cl);
        userListPanel = new UserListPanel(mainPanel, cl);
        createNewUserPanel = new CreateNewUserPanel();
    }

    private void setGroupLayout() {
//        GroupLayout freelancerListPanelLayout = new GroupLayout(freelancerListPanel);
        mainPanel.add(freelancerListPanel, FREELANCER_LIST);
        mainPanel.add(createNewFreelancerPanel, CREATE_NEW_FREELANCER);
        mainPanel.add(projectListPanel, PROJECT_LIST);
        mainPanel.add(createNewProjectPanel, CREATE_NEW_PROJECT);
        mainPanel.add(skillListPanel, SKILL_LIST);
        mainPanel.add(createNewSkillPanel, CREATE_NEW_SKILL);
        mainPanel.add(userDetailPanel, USER_DETAIL);
        mainPanel.add(editUserDetailPanel, EDIT_USER_DETAIL);
        mainPanel.add(customerListPanel, CUSTOMER_LIST);
        mainPanel.add(createNewCustomerPanel, CREATE_NEW_CUSTOMER);
        mainPanel.add(plainingPanel, PLAINING);
        mainPanel.add(userListPanel, USER_LIST);
        mainPanel.add(createNewUserPanel, CREATE_NEW_USER);
    }

    private void handleLoginInfo() {
        User loginUser = SessionManager.getCurrentUser();
        String fullName = loginUser.getFullName();
        userMenu.setText("Hồ sơ ("+fullName+")");
        
    }
}
