/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.DuAnController;
import controller.FreelancerController;
import controller.KhachHangController;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.DuAn;
import model.KhachHang;
import util.Common;

/**
 *
 * @author thisi
 */
public class PlainingPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlainingPanel
     */
    DuAnController duAnController;
    KhachHangController khachHangController;
    FreelancerController freelancerController;

    public PlainingPanel(JPanel mainPanel, CardLayout cl) {
        initComponents();
        duAnController = new DuAnController();
        khachHangController = new KhachHangController();
        freelancerController = new FreelancerController();

        fetchDuAnComboBox();
        firstLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addNewButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        motaInput = new javax.swing.JTextArea();
        duanComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        startInput = new javax.swing.JTextField();
        endInput = new javax.swing.JTextField();
        tenkhInput = new javax.swing.JTextField();
        emailkhInput = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sodienthoaikhInput = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        freelancerScrollPane = new javax.swing.JScrollPane();

        jLabel3.setText("LẬP KẾ HOẠCH DỰ ÁN");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Tên dự án");

        jLabel6.setText("Freelancer");

        addNewButton.setText("Cập nhật kế hoạch");
        addNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Làm mới");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Mô tả");

        motaInput.setEditable(false);
        motaInput.setColumns(20);
        motaInput.setRows(5);
        jScrollPane1.setViewportView(motaInput);

        duanComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                duanComboBoxItemStateChanged(evt);
            }
        });

        jLabel8.setText("Ngày bắt đầu");

        jLabel9.setText("Ngày kết thúc");

        jLabel10.setText("Tên khách hàng");

        startInput.setEditable(false);

        endInput.setEditable(false);

        tenkhInput.setEditable(false);

        emailkhInput.setEditable(false);

        jLabel11.setText("Email");

        sodienthoaikhInput.setEditable(false);

        jLabel12.setText("Số điện thoại");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(addNewButton)
                        .addGap(39, 39, 39)
                        .addComponent(clearButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)
                                .addComponent(duanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(endInput, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(startInput, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(8, 8, 8)
                                    .addComponent(tenkhInput, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel11))
                                    .addGap(20, 20, 20)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(emailkhInput, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sodienthoaikhInput, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(freelancerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(duanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(startInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(endInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tenkhInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(emailkhInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(sodienthoaikhInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6)
                    .addComponent(freelancerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewButton)
                    .addComponent(clearButton))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void duanComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_duanComboBoxItemStateChanged
        // TODO add your handling code here:
        loadInfo();
        checkFreelancerComboBox();
    }//GEN-LAST:event_duanComboBoxItemStateChanged

    private void addNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewButtonActionPerformed
        // TODO add your handling code here:

        int result = JOptionPane.showConfirmDialog(
                this, // parent component
                "Bạn có chắc chắn muốn lập kế hoạch?", // message
                "Xác nhận", // title
                JOptionPane.YES_NO_OPTION
        );
        if (result == JOptionPane.YES_OPTION) {
            int num = 0;

            DuAn da = (DuAn) duanComboBox.getSelectedItem();
            duAnController.clearDuAnFreelancerByDuAnId(da.getId());
            int checkedCount = 0;
            for (JCheckBox cb : checkBoxes.values()) {
                if (cb.isSelected()) {
                    checkedCount++;
                }
            }
            if (checkedCount == 0) {
                JOptionPane.showMessageDialog(this, "Lập kế hoạch thành công");
                return;
            } else {
                for (Map.Entry<Integer, JCheckBox> entry : checkBoxes.entrySet()) {
                    Integer key = entry.getKey();
                    JCheckBox cb = entry.getValue();
                    if (cb.isSelected()) {
                        num = duAnController.insertDuAnFreelancer(da.getId(), key);

                    }
                }
            }

            if (num > 0) {
                JOptionPane.showMessageDialog(this, "Lập kế hoạch thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Lập kế hoạch thất bại");
            }
        }


    }//GEN-LAST:event_addNewButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<DuAn> duanComboBox;
    private javax.swing.JTextField emailkhInput;
    private javax.swing.JTextField endInput;
    private javax.swing.JScrollPane freelancerScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea motaInput;
    private javax.swing.JTextField sodienthoaikhInput;
    private javax.swing.JTextField startInput;
    private javax.swing.JTextField tenkhInput;
    // End of variables declaration//GEN-END:variables
    private final Map<Integer, JCheckBox> checkBoxes = new LinkedHashMap<>();

    private void fetchDuAnComboBox() {
        List<Map<String, Object>> ds = duAnController.getAll();
        List<DuAn> dsDuAn = new ArrayList<>();
        duanComboBox.removeAllItems();
        for (Map<String, Object> i : ds) {
            DuAn da = new DuAn();
            da.setId((int) i.get("id"));
            da.setTen(i.get("ten").toString());
            da.setNgayBatDau(Common.convertStringToLocalDate(i.get("ngay_bat_dau").toString()));
            da.setNgayKetThuc(Common.convertStringToLocalDate(i.get("ngay_ket_thuc").toString()));
            da.setMaKhachHang((int) i.get("ma_khach_hang"));
            da.setMota(i.get("mota").toString());
            duanComboBox.addItem(da);
        }
    }

    private void addFreelancerToScrollPane() {
        JPanel freelancerPanel = new JPanel();
        freelancerPanel.setLayout(new BoxLayout(freelancerPanel, BoxLayout.Y_AXIS));
        List<Map<String, Object>> ds = freelancerController.getAll();
        for (Map<String, Object> f : ds) {
            JCheckBox cb = new JCheckBox(f.get("ho_ten") + " (Kỹ năng: " + f.get("dskynang") + " _ Trạng thái: " + f.get("trangthai") + ")");
            checkBoxes.put((int) f.get("id"), cb);
            freelancerPanel.add(cb);
        }
        freelancerScrollPane.setViewportView(freelancerPanel);

        checkFreelancerComboBox();

    }

    private void checkFreelancerComboBox() {
        for (JCheckBox cb : checkBoxes.values()) {
            cb.setSelected(false);
        }
        DuAn da = (DuAn) duanComboBox.getSelectedItem();
        // get freelancer id from du an check
        List<Map<String, Object>> dsDuAnFreelancer = duAnController.getDuAnFreelancerByDuAnId(da.getId());
        for (Map<String, Object> f : dsDuAnFreelancer) {
            int freelancerId = (int) f.get("freelancer_id");
            if (checkBoxes.containsKey(freelancerId)) {
                checkBoxes.get(freelancerId).setSelected(true);
            }
        }
    }

    private void firstLoad() {
        loadInfo();
        addFreelancerToScrollPane();
    }

    private void loadInfo() {
        DuAn da = (DuAn) duanComboBox.getSelectedItem();

        startInput.setText(Common.convertLocalDateToString(da.getNgayBatDau()));
        endInput.setText(Common.convertLocalDateToString(da.getNgayKetThuc()));
        motaInput.setText(da.getMota());

        KhachHang kh = khachHangController.findById(da.getMaKhachHang());

        tenkhInput.setText(kh.getTen());
        sodienthoaikhInput.setText(kh.getSoDienThoai());
        emailkhInput.setText(kh.getEmail());
    }
}
