/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.DuAnController;
import controller.KhachHangController;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.DuAn;
import model.KhachHang;

/**
 *
 * @author thisi
 */
public class ProjectListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProjectListPanel
     */
    private JPanel mainPanel;
    private CardLayout cl;

    private DuAnController duAnController;
    private KhachHangController khachHangController;

    public ProjectListPanel(JPanel mainPanel, CardLayout cl) {
        initComponents();
        this.mainPanel = mainPanel;
        this.cl = cl;

        duAnController = new DuAnController();
        khachHangController = new KhachHangController();
        fetchProjectTable();
        formReady(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        duanTable = new javax.swing.JTable();
        addNewProjectButton = new javax.swing.JButton();
        plainingButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tenInput = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        motaInput = new javax.swing.JTextArea();
        idInput = new javax.swing.JTextField();
        khachhangComboBox = new javax.swing.JComboBox<>();
        startSpinner = new javax.swing.JSpinner();
        endSpinner = new javax.swing.JSpinner();

        jLabel1.setText("DANH SÁCH DỰ ÁN");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Danh sách");

        duanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã dự án", "Tên dự án", "Bắt đầu", "Kết thúc", "Khách hàng"
            }
        ));
        duanTable.setSelectionBackground(new java.awt.Color(255, 255, 204));
        duanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duanTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(duanTable);

        addNewProjectButton.setText("➕ Thêm mới");
        addNewProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewProjectButtonActionPerformed(evt);
            }
        });

        plainingButton.setBackground(new java.awt.Color(255, 255, 204));
        plainingButton.setForeground(new java.awt.Color(51, 51, 255));
        plainingButton.setText("Lập kế hoạch");
        plainingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plainingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addNewProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plainingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addNewProjectButton)
                    .addComponent(plainingButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Thông tin chi tiết");

        jLabel4.setText("Mã dự án");

        jLabel5.setText("Tên dự án");

        jLabel6.setText("Bắt đầu");

        jLabel7.setText("Khách hàng");

        jLabel8.setText("Kết thúc");

        jLabel12.setText("Mô tả");

        updateButton.setText("Cập nhật");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 102, 102));
        deleteButton.setText("Xóa");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        motaInput.setColumns(20);
        motaInput.setRows(5);
        jScrollPane2.setViewportView(motaInput);

        idInput.setEditable(false);

        khachhangComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachhangComboBoxActionPerformed(evt);
            }
        });

        startSpinner.setModel(new javax.swing.SpinnerDateModel());

        endSpinner.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idInput)
                    .addComponent(khachhangComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tenInput)
                    .addComponent(startSpinner)
                    .addComponent(endSpinner))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tenInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(startSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(endSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(khachhangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNewProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewProjectButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Thêm kỹ năng mới mới");
        cl.show(mainPanel, CREATE_NEW_PROJECT);
    }//GEN-LAST:event_addNewProjectButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        int result = JOptionPane.showConfirmDialog(
                this, // parent component
                "Bạn có chắc chắn muốn xóa?", // message
                "Xác nhận", // title
                JOptionPane.YES_NO_OPTION
        );

        if (result == JOptionPane.YES_OPTION) {
            String id = idInput.getText();
            if (!id.equals("")) {
                int num = duAnController.delete(Integer.valueOf(id));
                if (num != 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    fetchProjectTable();
                    clearForm();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void plainingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plainingButtonActionPerformed
        // TODO add your handling code here:
        cl.show(mainPanel, PLAINING);
    }//GEN-LAST:event_plainingButtonActionPerformed

    private void duanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duanTableMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int col = 0; // id column
        String s = source.getModel().getValueAt(row, col) + "";

        formReady(Integer.valueOf(s));
    }//GEN-LAST:event_duanTableMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        String id = idInput.getText();
        String ten = tenInput.getText();
        Date start = (Date) startSpinner.getValue();
        LocalDate starDate = start.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Date end = (Date) endSpinner.getValue();
        LocalDate endDate = end.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String mota = motaInput.getText();
        KhachHang kh = (KhachHang) khachhangComboBox.getSelectedItem();

        if (id.isEmpty() || ten.isEmpty() || kh == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin");
            return;
        }

        DuAn duAn = new DuAn(Integer.valueOf(id), ten, starDate, endDate, kh.getId(), mota);
        int result = duAnController.update(duAn);
        if (result != 0) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            fetchProjectTable();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void khachhangComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachhangComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_khachhangComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewProjectButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable duanTable;
    private javax.swing.JSpinner endSpinner;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<KhachHang> khachhangComboBox;
    private javax.swing.JTextArea motaInput;
    private javax.swing.JButton plainingButton;
    private javax.swing.JSpinner startSpinner;
    private javax.swing.JTextField tenInput;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    private String CREATE_NEW_PROJECT = "CREATE_NEW_PROJECT_PANEL";
    private String PLAINING = "PLAINING_PANEL";

    private void fetchProjectTable() {
        List<Map<String, Object>> dsDuAn = duAnController.getAll();
        DefaultTableModel tableModel = (DefaultTableModel) duanTable.getModel();
        tableModel.setRowCount(0);
        // Update the project table with the fetched data
        for (Map<String, Object> duAn : dsDuAn) {
            // Add each project to the table model
            Object[] row = new Object[]{
                duAn.get("id"),
                duAn.get("ten"),
                duAn.get("ngay_bat_dau"),
                duAn.get("ngay_ket_thuc"),
                duAn.get("tenkh")
            };
            tableModel.addRow(row);
        }
    }

    private void formReady(int duanId) {
        DuAn da;
        KhachHang kh;
        
        List<KhachHang> dsKhachHang = khachHangController.getAll();
        khachhangComboBox.removeAllItems();
        for (KhachHang k : dsKhachHang) {
            khachhangComboBox.addItem(k);
        }

        // format spinner
        JSpinner.DateEditor seditor = new JSpinner.DateEditor(startSpinner, "yyyy-MM-dd");
        startSpinner.setEditor(seditor);
        JSpinner.DateEditor eeditor = new JSpinner.DateEditor(endSpinner, "yyyy-MM-dd");
        endSpinner.setEditor(eeditor);

        if (duanId != 0) {
            da = duAnController.findById(duanId);
        } else {
            int firstRowId = (int) duanTable.getValueAt(0, 0);
            da = duAnController.findById(firstRowId);
        }
        kh = khachHangController.findById(da.getMaKhachHang());

        idInput.setText(String.valueOf(da.getId()));
        tenInput.setText(da.getTen());
        
        
        LocalDate ngaybatdau = da.getNgayBatDau();
        if (ngaybatdau != null) {
            Date date = Date.from(ngaybatdau.atStartOfDay(ZoneId.systemDefault()).toInstant());
            startSpinner.setValue(date);
        }
        
        
        LocalDate ngayketthuc = da.getNgayKetThuc();
        if (ngaybatdau != null) {
            Date date = Date.from(ngayketthuc.atStartOfDay(ZoneId.systemDefault()).toInstant());
            endSpinner.setValue(date);
        }

        motaInput.setText(da.getMota());
        khachhangComboBox.setSelectedItem(kh);
    }

    private void clearForm() {
        idInput.setText("");
        tenInput.setText("");
        startSpinner.setValue(new Date());
        endSpinner.setValue(new Date());
        motaInput.setText("");
        khachhangComboBox.setSelectedIndex(-1);
    }
    
    
    public void reloadTable() {
        fetchProjectTable();
    }

}
